# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/sm8450-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter pdx223 pdx224,$(TARGET_DEVICE)),)

endif
